// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb5UNY7w3DmkVrxUbGnDi4QhuKUUvHMiI',
    appId: '1:647643798659:web:73ff49bb6702dd366fcfb6',
    messagingSenderId: '647643798659',
    projectId: 'notometro-a4117',
    authDomain: 'notometro-a4117.firebaseapp.com',
    storageBucket: 'notometro-a4117.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRh7VJKkrhzGPHZJxWXj9P1TgnhmLiXo',
    appId: '1:647643798659:android:0c5671ada238c6a26fcfb6',
    messagingSenderId: '647643798659',
    projectId: 'notometro-a4117',
    storageBucket: 'notometro-a4117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcW5M_kHxwDuYPUfKTs5b-SM1XIMWGD8I',
    appId: '1:647643798659:ios:349f939c9826c8f06fcfb6',
    messagingSenderId: '647643798659',
    projectId: 'notometro-a4117',
    storageBucket: 'notometro-a4117.firebasestorage.app',
    iosBundleId: 'com.example.notasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcW5M_kHxwDuYPUfKTs5b-SM1XIMWGD8I',
    appId: '1:647643798659:ios:349f939c9826c8f06fcfb6',
    messagingSenderId: '647643798659',
    projectId: 'notometro-a4117',
    storageBucket: 'notometro-a4117.firebasestorage.app',
    iosBundleId: 'com.example.notasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb5UNY7w3DmkVrxUbGnDi4QhuKUUvHMiI',
    appId: '1:647643798659:web:ed1cd7102d5384006fcfb6',
    messagingSenderId: '647643798659',
    projectId: 'notometro-a4117',
    authDomain: 'notometro-a4117.firebaseapp.com',
    storageBucket: 'notometro-a4117.firebasestorage.app',
  );
}
